// flow-typed signature: 757f46ea726cf4b6a6dced2cfa4b322a
// flow-typed version: <<STUB>>/node-sass-glob-importer_v^5.1.3/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-sass-glob-importer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-sass-glob-importer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-sass-glob-importer/dist/cli' {
  declare module.exports: any;
}

declare module 'node-sass-glob-importer/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-sass-glob-importer/dist/cli.js' {
  declare module.exports: $Exports<'node-sass-glob-importer/dist/cli'>;
}
declare module 'node-sass-glob-importer/dist/index.js' {
  declare module.exports: $Exports<'node-sass-glob-importer/dist/index'>;
}
